spring:
  datasource:
    url: ''
    username: ''
    password: ''
  mail:
    host: 'smtp.gmail.com'
    username: ''
    password: ''
    properties:
      mail:
        transport:
          protocol: 'smtp'
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    port: 587