JWT_SECRET: '9AEW57AzDzHiamTadS3zr3g33g34grgb3MxAưewe0/xJEsx7RpYRorLUDEUugrQ=='
JWT_TIME_ACCESS_TOKEN: 3600000
JWT_TIME_REFRESH_TOKEN: 31536000000
BASE_API: '/api/v1'
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: 'smtp.gmail.com'
    username: 'Lannhatthuy@gmail.com'
    password: 'iguhvidnouiyjoix'
    properties:
      mail:
        transport:
          protocol: 'smtp'
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    port: 587